# Generated by Django 5.0.2 on 2024-03-09 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Age', models.PositiveIntegerField()),
                ('Gaurdian', models.CharField(max_length=25)),
                ('Aadhaarnumber', models.PositiveIntegerField(blank=True, null=True)),
                ('Pannumber', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loanamount', models.PositiveIntegerField()),
                ('Loanintrest', models.PositiveIntegerField()),
                ('Loanholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuzhuapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Emi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repay', models.PositiveIntegerField()),
                ('Intrest', models.PositiveIntegerField()),
                ('Savings', models.PositiveIntegerField()),
                ('Sandha', models.PositiveIntegerField()),
                ('mon', models.DateField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuzhuapp.loan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuzhuapp.member')),
            ],
        ),
    ]
