# Generated by Django 5.0.2 on 2024-03-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuzhuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
