# Generated by Django 5.0.2 on 2024-03-12 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuzhuapp', '0004_remove_emi_loan_rename_member_emi_mem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Aadhaarnumber',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
